### PR TITLE
Reduce size of default Parcel install

### LINKED ISSUE #4729: Babel Transformer tries to load @babel/core relative to runtime
# 🐛 bug report

The babel transformer tries to require @babel/core from node_modules/@parcel/runtime-browser-hmr/lib  (“the users babel-core”), but there is no babel-core here. Then Yarn 2 throws

Note: this only fails in workspaces

A regression caused by https://github.com/parcel-bundler/parcel/pull/4526

## 😯 Current Behavior

```
Error: Cannot find module '@babel/core' from '.../berry-repro/.yarn/cache/@parcel-runtime-browser-hmr-npm-2.0.0-nightly.290-56e0fefb14-3.zip/node_modules/@parcel/runtime-browser-hmr/lib'
    at .../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:115:35
    at processDirs (.../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:268:39)
    at loadNodeModules (.../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:293:9)
    at init (.../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:104:16)
    at .../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:90:18
    at maybeRealpath (.../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:41:9)
    at resolve (.../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:84:5)
    at .../berry-repro/.yarn/unplugged/@parcel-utils-npm-2.0.0-nightly.290-51f06aaf7f/node_modules/@parcel/utils/lib/promisify.js:6:13
    at new Promise (<anonymous>)
    at .../berry-repro/.yarn/unplugged/@parcel-utils-npm-2.0.0-nightly.290-51f06aaf7f/node_modules/@parcel/utils/lib/promisify.js:5:12
```

Or
`console: (node:75178) [MODULE_NOT_FOUND] Error: @parcel/runtime-browser-hmr tried to access @babel/core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
`

## 💁 Possible Solution

- Do we need another flag for the babel transformer to know if it should use the bundled babel/core?
- The alternative would be requiring all runtimes to have babel/core installed

## 💻 Code Sample

```sh
yarn set version berry
echo '{"name": "test2", "workspaces": ["parcel"],"private": true}' > package.json
mkdir parcel
cd parcel
yarn init
yarn add -D parcel@nightly
touch index.js
yarn parcel index.js --no-autoinstall
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2
| Yarn | 2

### PR DESCRIPTION
**Pull request by devongovett**
This reduces the size of `node_modules` when installing Parcel. Rather than installing all plugins included in the default config, we only install a small subset of the most commonly used plugins (basically the JS pipeline). Other plugins are listed in the default config and auto installed into the user's project along with their peer dependencies on demand. This means that you only get the plugins you actually use in your project. The downside is a few more entries in your project's package.json in these cases.

This is implemented by resolving plugins relative to the user's project rather than the config when the config is in `node_modules` and the plugin is not listed in the `dependencies` of the config's package.json. The versions must still be listed in `parcelDependencies` in the config's package.json, which tells parcel which version range of the plugin to auto install into the user's project. The package manager will also verify that a compatible version is installed when loading the plugin.

This removes most of the `options.packageManager.require` calls from plugins. Instead, the plugin dependencies are listed either as `dependencies` or `peerDependencies`, based on whether the user will also likely need to access the same dependency. For example, `@babel/core` and `typescript` are peer dependencies, but `js-yaml` is a normal dependency. For peer dependencies, two entries will be auto installed into the project's package.json.

Closes #4729, T-630

### CODE REVIEW

File: packages/configs/default/index.json [hunk 1]
```diff
@@ -68,8 +68,6 @@
   "resolvers": ["@parcel/resolver-default"],
   "reporters": [
     "@parcel/reporter-cli",
-    "@parcel/reporter-dev-server",
-    "@parcel/reporter-bundle-analyzer",
-    "@parcel/reporter-bundle-buddy"
```
Comment (devongovett) [inline packages/configs/default/index.json:73]: Removed these temporarily. The ideal way to run these is via a `--reporter` CLI option (which we have yet to add).

Comment (mischnic) [reply packages/configs/default/index.json:73]: Including the dev server? Sure?

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.28s | +55.00ms |
| Cached | 651.00ms | +29.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/index.33d06174.js | 1.11kb | +0.00b | 689.00ms | +48.00ms ⚠️ |
| dist/legacy/index.html | 701.00b | +0.00b | 689.00ms | +48.00ms ⚠️ |
| dist/legacy/index.44edca46.css | 77.00b | +0.00b | 1.21s | +64.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 60.00ms | -21.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 84.00ms | +27.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 22.65s | -396.00ms |
| Cached | 10.31s | +172.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/PermalinkedComment.77f121c4.js | 4.20kb | +0.00b | 981.00ms | +173.00ms ⚠️ |
| dist/UserProfile.125b5ebe.js | 1.76kb | +0.00b | 982.00ms | +174.00ms ⚠️ |
| dist/NotFound.d769112d.js | 530.00b | +0.00b | 271.00ms | +24.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 483.35kb | +0.00b | 86.00ms | +6.00ms ⚠️ |
| dist/PermalinkedComment.77f121c4.js | 4.20kb | +0.00b | 86.00ms | +6.00ms ⚠️ |
| dist/UserProfile.125b5ebe.js | 1.76kb | +0.00b | 86.00ms | +6.00ms ⚠️ |
| dist/NotFound.d769112d.js | 530.00b | +0.00b | 248.00ms | -17.00ms 🚀 |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 71.00ms | +8.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.09m | -3.10s |
| Cached | 3.17s | -118.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/card.ecae978d.js | 54.02kb | +0.00b | 9.82s | -577.00ms 🚀 |
| dist/Modal.a2c499cb.js | 39.18kb | +0.00b | 5.10s | +895.00ms ⚠️ |
| dist/component.fa4e42d1.js | 30.82kb | +0.00b | 4.38s | +642.00ms ⚠️ |
| dist/esm.6bc5d42c.js | 27.67kb | +0.00b | 11.94s | +1.61s ⚠️ |
| dist/component.63b8a376.js | 22.54kb | +0.00b | 5.09s | +904.00ms ⚠️ |
| dist/DatePicker.cbcf2d18.js | 21.20kb | +0.00b | 6.96s | -3.29s 🚀 |
| dist/js.4b5d27df.js | 16.55kb | +0.00b | 5.08s | +895.00ms ⚠️ |
| dist/dropzone.a58778e7.js | 16.06kb | +0.00b | 12.75s | -3.81s 🚀 |
| dist/workerHasher.09e24457.js | 11.90kb | +0.00b | 7.78s | +761.00ms ⚠️ |
| dist/component.f521dd8b.js | 6.20kb | +0.00b | 4.75s | +727.00ms ⚠️ |
| dist/card.1a9729d8.js | 5.71kb | +0.00b | 9.81s | -1.08s 🚀 |
| dist/EmojiPickerComponent.ca69a3c9.js | 3.62kb | +0.00b | 7.78s | -946.00ms 🚀 |
| dist/png-chunks-extract.e6351d92.js | 3.55kb | +0.00b | 5.08s | +895.00ms ⚠️ |
| dist/Modal.00beb515.js | 3.14kb | +0.00b | 1.25s | +75.00ms ⚠️ |
| dist/16.cf92dee6.js | 2.49kb | +0.00b | 1.25s | +93.00ms ⚠️ |
| dist/ResourcedEmojiComponent.0df891ba.js | 2.15kb | +0.00b | 7.78s | -2.35s 🚀 |
| dist/date.f35453a2.js | 1.96kb | +0.00b | 5.86s | +1.10s ⚠️ |
| dist/images.861d8ede.js | 1.90kb | +0.00b | 6.09s | +1.32s ⚠️ |
| dist/feedback.ddd45d32.js | 1.86kb | +0.00b | 6.96s | -3.25s 🚀 |
| dist/16.4dbc75f9.js | 1.86kb | +0.00b | 5.30s | +396.00ms ⚠️ |
| dist/browser.ba398ea7.js | 1.82kb | +0.00b | 12.78s | -5.08s 🚀 |
| dist/16.934d2c3d.js | 1.79kb | +0.00b | 5.03s | +715.00ms ⚠️ |
| dist/workerHasher.afb52a72.js | 1.75kb | +0.00b | 7.78s | +765.00ms ⚠️ |
| dist/workerHasher.42458950.js | 1.75kb | +0.00b | 18.00s | +4.82s ⚠️ |
| dist/list-number.95becf64.js | 1.68kb | +0.00b | 6.09s | +1.21s ⚠️ |
| dist/status.5568e78d.js | 1.68kb | +0.00b | 6.37s | +825.00ms ⚠️ |
| dist/code.94d6ed50.js | 1.61kb | +0.00b | 5.86s | +747.00ms ⚠️ |
| dist/link.b4c4afb6.js | 1.53kb | +0.00b | 6.09s | +1.21s ⚠️ |
| dist/heading3.0c0fe1f4.js | 1.51kb | +0.00b | 10.29s | +5.12s ⚠️ |
| dist/16.2a10e9af.js | 1.51kb | +0.00b | 6.41s | +2.00s ⚠️ |
| dist/16.d564a7d9.js | 1.46kb | +0.00b | 4.93s | +668.00ms ⚠️ |
| dist/16.01c01dd6.js | 1.46kb | +0.00b | 6.36s | +1.95s ⚠️ |
| dist/emoji.4f12a585.js | 1.45kb | +0.00b | 5.86s | +1.09s ⚠️ |
| dist/16.81d1aa0c.js | 1.45kb | +0.00b | 1.25s | +76.00ms ⚠️ |
| dist/16.897e8807.js | 1.44kb | +0.00b | 5.71s | +1.09s ⚠️ |
| dist/16.c2dce044.js | 1.40kb | +0.00b | 5.71s | +1.09s ⚠️ |
| dist/heading5.bde11017.js | 1.40kb | +0.00b | 6.96s | +1.79s ⚠️ |
| dist/expand.ca6be77b.js | 1.38kb | +0.00b | 6.96s | -3.25s 🚀 |
| dist/16.ac96fdd0.js | 1.36kb | +0.00b | 5.30s | +396.00ms ⚠️ |
| dist/16.620d8c15.js | 1.34kb | +0.00b | 1.25s | +91.00ms ⚠️ |
| dist/heading2.1511a751.js | 1.33kb | +0.00b | 6.37s | +1.21s ⚠️ |
| dist/16.e0980eea.js | 1.32kb | +0.00b | 5.30s | +379.00ms ⚠️ |
| dist/16.990be6f2.js | 1.31kb | +0.00b | 5.71s | +1.09s ⚠️ |
| dist/mention.e2501ad0.js | 1.29kb | +0.00b | 6.25s | +1.37s ⚠️ |
| dist/heading4.1abfeb0a.js | 1.29kb | +0.00b | 10.29s | +5.12s ⚠️ |
| dist/Modal.b44f65e1.js | 1.28kb | +0.00b | 5.08s | +901.00ms ⚠️ |
| dist/16.30ebc170.js | 1.27kb | +0.00b | 1.25s | +75.00ms ⚠️ |
| dist/layout.6a9de36b.js | 1.27kb | +0.00b | 6.09s | +1.22s ⚠️ |
| dist/16.3ba7b0ec.js | 1.27kb | +0.00b | 5.30s | +878.00ms ⚠️ |
| dist/16.2ec03e4f.js | 1.26kb | +0.00b | 6.16s | +1.57s ⚠️ |
| dist/16.b9cdc131.js | 1.26kb | +0.00b | 6.36s | +1.94s ⚠️ |
| dist/16.98030c60.js | 1.26kb | +0.00b | 5.30s | +885.00ms ⚠️ |
| dist/16.c20ef86c.js | 1.26kb | +0.00b | 4.93s | +668.00ms ⚠️ |
| dist/divider.9a733dfe.js | 1.25kb | +0.00b | 5.86s | +1.09s ⚠️ |
| dist/quote.be70ca39.js | 1.25kb | +0.00b | 6.37s | +825.00ms ⚠️ |
| dist/component.3a931beb.js | 1.23kb | +0.00b | 4.35s | +649.00ms ⚠️ |
| dist/action.88cd1e67.js | 1.23kb | +0.00b | 5.71s | +1.06s ⚠️ |
| dist/16.7b2e1497.js | 1.23kb | +0.00b | 4.35s | +649.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.c2d3f430.js | 1.23kb | +0.00b | 9.81s | -1.01s 🚀 |
| dist/decision.0740ec10.js | 1.21kb | +0.00b | 5.86s | +1.09s ⚠️ |
| dist/panel-warning.9b047bba.js | 1.21kb | +0.00b | 6.25s | +1.23s ⚠️ |
| dist/16.c890a474.js | 1.18kb | +0.00b | 5.71s | +1.09s ⚠️ |
| dist/list.e4113e60.js | 1.18kb | +0.00b | 6.09s | +1.21s ⚠️ |
| dist/heading1.cf012b35.js | 1.18kb | +0.00b | 6.37s | +1.21s ⚠️ |
| dist/panel-error.0c73ee4f.js | 1.11kb | +0.00b | 6.25s | +1.24s ⚠️ |
| dist/panel.53ea0317.js | 1.10kb | +0.00b | 6.72s | +1.70s ⚠️ |
| dist/table.23e2141c.js | 1.09kb | +0.00b | 6.37s | +816.00ms ⚠️ |
| dist/panel-success.b56c18fb.js | 1.05kb | +0.00b | 6.25s | +1.24s ⚠️ |
| dist/panel-note.d5e6a337.js | 1.05kb | +0.00b | 6.25s | +1.24s ⚠️ |
| dist/media-picker-analytics-error-boundary.16608041.js | 1003.00b | +0.00b | 12.74s | +685.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.64c19024.js | 999.00b | +0.00b | 9.81s | -646.00ms 🚀 |
| dist/media-card-analytics-error-boundary.60a98f4f.js | 999.00b | +0.00b | 17.94s | +4.76s ⚠️ |
| dist/simpleHasher.931d48e8.js | 755.00b | +0.00b | 7.78s | +743.00ms ⚠️ |
| dist/simpleHasher.d4526885.js | 755.00b | +0.00b | 16.00s | +2.19s ⚠️ |
| dist/index.html | 119.00b | +0.00b | 3.34s | +394.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.dbba2cf0.js | 2.46mb | +0.00b | 662.00ms | +35.00ms ⚠️ |
| dist/Modal.a2c499cb.js | 39.18kb | +0.00b | 592.00ms | -35.00ms 🚀 |
| dist/component.fa4e42d1.js | 30.82kb | +0.00b | 661.00ms | +34.00ms ⚠️ |
| dist/component.63b8a376.js | 22.54kb | +0.00b | 592.00ms | -34.00ms 🚀 |
| dist/js.4b5d27df.js | 16.55kb | +0.00b | 592.00ms | -34.00ms 🚀 |
| dist/png-chunks-extract.e6351d92.js | 3.55kb | +0.00b | 592.00ms | -34.00ms 🚀 |
| dist/Modal.00beb515.js | 3.14kb | +0.00b | 578.00ms | -38.00ms 🚀 |
| dist/16.cf92dee6.js | 2.49kb | +0.00b | 579.00ms | -36.00ms 🚀 |
| dist/16.81d1aa0c.js | 1.45kb | +0.00b | 578.00ms | -38.00ms 🚀 |
| dist/16.620d8c15.js | 1.34kb | +0.00b | 578.00ms | -38.00ms 🚀 |
| dist/Modal.b44f65e1.js | 1.28kb | +0.00b | 592.00ms | -34.00ms 🚀 |
| dist/16.30ebc170.js | 1.27kb | +0.00b | 578.00ms | -38.00ms 🚀 |
| dist/component.3a931beb.js | 1.23kb | +0.00b | 662.00ms | +35.00ms ⚠️ |
| dist/16.7b2e1497.js | 1.23kb | +0.00b | 662.00ms | +35.00ms ⚠️ |
| dist/media-viewer-analytics-error-boundary.57caec83.js | 995.00b | +0.00b | 763.00ms | +41.00ms ⚠️ |
| dist/index.html | 119.00b | +0.00b | 594.00ms | +30.00ms ⚠️ |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 15.61s | +87.00ms |
| Cached | 709.00ms | +87.00ms ⚠️ |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/Three.js | 580.59kb | +0.00b | 128.00ms | +14.00ms ⚠️ |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/289532843452793352)**

File: packages/configs/default/index.json (hunk 1 above)
Comment (devongovett) [reply packages/configs/default/index.json:73]: Dev server is still there...

File: packages/core/parcel/src/cli.js [hunk 2]
```diff
@@ -329,7 +329,8 @@ async function normalizeOptions(command): Promise<InitialParcelOptions> {
   let nodeEnv;
   if (command.name() === 'build') {
     nodeEnv = process.env.NODE_ENV || 'production';
-    command.autoinstall = false;
+    // Autoinstall unless explicitly disabled or we detect a CI environment.
+    command.autoinstall = command.autoinstall === false || process.env.CI ? false : true;
```
Comment (wbinnssmith) [inline packages/core/parcel/src/cli.js:333]:
```suggestion
    command.autoinstall = !(command.autoinstall === false || process.env.CI);
```

File: packages/validators/typescript/src/TypeScriptValidator.js [hunk 3]
```diff
@@ -129,6 +124,7 @@ async function tryCreateLanguageService(
       langServiceCache[config.configHash] = {
         configHost,
         host,
+        // $FlowFixMe - complains about methods being readonly...
```
Comment (wbinnssmith) [inline packages/validators/typescript/src/TypeScriptValidator.js:127]: nit: this can be narrowed to the specific violation, e.g. `// $FlowFixMe[violation-name]`

Comment (devongovett) [reply packages/validators/typescript/src/TypeScriptValidator.js]: Ah TIL! It's actually two violations but I added them both

File: packages/transformers/babel/src/BabelTransformer.js [hunk 4]
```diff
@@ -15,10 +15,6 @@ export default (new Transformer({
     return preSerialize(config);
   },
 
-  postDeserializeConfig({config, options}) {
```
Comment (mischnic) [inline packages/transformers/babel/src/BabelTransformer.js:18]: We can remove that from `@parcel/types` and the postcss transformer as well

File: packages/transformers/mdx/src/MDXTransformer.js [hunk 5]
```diff
@@ -1,22 +1,14 @@
...
-      }),
-    ]);
-
-    const compiled = await mdx(code);
+  async transform({asset}) {
+    let code = await asset.getCode();
+    let compiled = await mdx(code);
 
     asset.type = 'js';
+    // TODO: resolve @mdx-js/react relative to the plugin rather than the asset?
```
Comment (mischnic) [inline packages/transformers/mdx/src/MDXTransformer.js:11]: Could `@mdx-js/react` be a peer dependency instead?

File: packages/core/core/src/loadParcelPlugin.js [hunk 6]
```diff
@@ -10,35 +9,100 @@ import nullthrows from 'nullthrows';
...
+    let configContents = await options.inputFS.readFile(configPath, 'utf8');
     let alternatives = await findAlternativeNodeModules(
-      fs,
+      options.inputFS,
       pluginName,
       path.dirname(resolveFrom),
     );
     throw new ThrowableDiagnostic({
       diagnostic: {
         message: `Cannot find parcel plugin "${pluginName}"`,
```
Comment (mischnic) [inline packages/core/core/src/loadParcelPlugin.js:103]:
```suggestion
        message: `Cannot find Parcel plugin "${pluginName}"`,
```

File: packages/core/core/src/loadParcelPlugin.js [hunk 7]
```diff
@@ -10,35 +9,100 @@ import nullthrows from 'nullthrows';
...
+    }
+
+    let configContents = await options.inputFS.readFile(configPath, 'utf8');
     let alternatives = await findAlternativeNodeModules(
-      fs,
+      options.inputFS,
       pluginName,
       path.dirname(resolveFrom),
     );
     throw new ThrowableDiagnostic({
```
Comment (mischnic) [inline packages/core/core/src/loadParcelPlugin.js:101]: (Not really specific to the changes, but this reminds me of how `Cannot find Parcel plugin` would be printed even when Yarn failed, e.g. because there is no such package: https://github.com/parcel-bundler/parcel/issues/5750)

**Review by mischnic — APPROVED** [review]
