### ISSUE TITLE
Underscores aren't escaped in path when displaying an error

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#4057]
# 🐛 bug report

Might be a regression from from #4009

Actual error:
🚨 Error: Cannot find module 'url:~/static/data/2012/finalPerimeters_California_2012.geojson' from
'..../_foo/_bar/project/_xyz'

Is displayed as:
🚨 Error: Cannot find module 'url:~/static/data/2012/finalPerimeters*California*2012.geojson' from
'..../ _foo/_ bar/project/_xyz'
