### ISSUE TITLE
Parcel will not work with node > 12.16.3

### ISSUE THREAD

**Issue by Gaspacchio** [parcel-bundler/parcel#4681]
# 🐛 bug report

Running `parcel watch` or `parcel build` with node version > 12.16.3 fails with an error.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "presets": [
    [
      "@babel/preset-env",
      { "spec": true, "useBuiltIns": "usage", "corejs": 3 }
    ],
    ["minify", {}]
  ]
}

```

## 🤔 Expected Behavior

Parcel should build.

## 😯 Current Behavior

Parcel fails with the following error:

```
‼  Parser "assets\JSAsset" failed to initialize when processing asset "src\web\assets\js\main.js". Thre
w the following error:
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- C:\Users\project\node_modules\parcel-bundler\node_modules\@babel\prese
t-env\lib\polyfills\corejs3\usage-plugin.js
- C:\Users\project\node_modules\parcel-bundler\node_modules\@babel\prese
t-env\lib\index.js
- C:\Users\project\node_modules\parcel-bundler\src\transforms\babel\env.
js
- C:\Users\project\node_modules\parcel-bundler\src\transforms\babel\conf
ig.js
- C:\Users\project\node_modules\parcel-bundler\src\transforms\babel\tran
sform.js
- C:\Users\project\node_modules\parcel-bundler\src\assets\JSAsset.js    
- C:\Users\project\node_modules\parcel-bundler\src\Parser.js
- C:\Users\project\node_modules\parcel-bundler\src\Bundler.js
- C:\Users\project\node_modules\parcel-bundler\index.js
- C:\Users\project\node_modules\parcel-bundler\src\cli.js
- C:\Users\project\node_modules\parcel-bundler\bin\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (C:\Users\project\node_modules\v8-compile-cache\v8-compil
e-cache.js:161:20)
    at Object.<anonymous> (C:\Users\project\node_modules\parcel-bundler\
node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js:10:55)
    at Module._compile (C:\Users\project\node_modules\v8-compile-cache\v
8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19) falling back to RawAsset

...

×  Cannot read property 'length' of undefined
    at lineCounter (C:\Users\project\node_modules\parcel-bundler\src\uti
ls\lineCounter.js:3:30)
    at JSPackager.writeModule (C:\Users\project\node_modules\parcel-bund
ler\src\packagers\JSPackager.js:127:60)
    at async JSPackager.addAsset (C:\Users\project\node_modules\parcel-b
undler\src\packagers\JSPackager.js:88:5)
    at async Bundle._addDeps (C:\Users\project\node_modules\parcel-bundl
er\src\Bundle.js:250:5)
    at async Bundle._package (C:\Users\project\node_modules\parcel-bundl
er\src\Bundle.js:219:7)
    at async Promise.all (index 0)
    at async Bundle.package (C:\Users\project\node_modules\parcel-bundle
r\src\Bundle.js:202:5)
    at async Promise.all (index 1)
    at async Bundle.package (C:\Users\project\node_modules\parcel-bundle
r\src\Bundle.js:202:5)
    at async Bundler.bundle (C:\Users\project\node_modules\parcel-bundle
r\src\Bundler.js:325:27)
```

## 🔦 Context

I'm trying to build and develop a website using Parcel.

## 💻 Code Sample

CLI command: `"start": "parcel watch src/web/index.html -d dev/"`

Full repo is accessible here: https://gitlab.com/gaspacchio/back-to-the-future

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4|
| Node             |14.0.0|
| Yarn         | 1.22.4|
| Operating System | Windows 10 19041.264|

**Comment by mischnic** [comment]
I think you need to update all babel dependencies in your lockfile

**Comment by Gaspacchio** [comment]
I'll give it a try in a few minutes 🤞

**Comment by franky47** [comment]
I had the same issue, and it broke my build silently, shipping an empty bundle to production..

Missing dependencies should break the build, to let the CI/CD process know something went wrong.

**Comment by sPooKee** [comment]
@pukafever Would you be able to elaborate, what exactly you did?

I'm getting a similar error (Node 14.15.0):

```json
  "devDependencies": {
    "@babel/core": "^7.13.8",
    "babel-preset-minify": "^0.5.1",
    "parcel-bundler": "^1.12.4"
  },
  "dependencies": {
    "preact": "^10.5.12"
  }
```

**Error:**

```
% yarn start
yarn run v1.22.10
$ parcel src/index.html
Server running at http://localhost:1234
🚨  /src/index.js: Invalid Version: undefined
    at new SemVer (/node_modules/semver/semver.js:314:11)
    at compare (/node_modules/semver/semver.js:647:10)
    at lt (/node_modules/semver/semver.js:688:10)
    at /node_modules/@babel/preset-env/lib/index.js:276:22
    at Object.default (/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12)
    at getEnvPlugins (/node_modules/parcel-bundler/src/transforms/babel/env.js:62:34)
    at getEnvConfig (/node_modules/parcel-bundler/src/transforms/babel/env.js:12:25)
    at async getBabelConfig (/node_modules/parcel-bundler/src/transforms/babel/config.js:32:19)
    at async babelTransform (/node_modules/parcel-bundler/src/transforms/babel/transform.js:6:16)
    at async JSAsset.pretransform (/node_modules/parcel-bundler/src/assets/JSAsset.js:83:5)
```

**Comment by egriff38** [comment]
I've also encountered this same issue just recently with 2 separate applications using parcel 1.12.4, node v14.15. Same error message as @sPooKee. The applications were compiling fine this past week, which is the strange thing.

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/5943
