### ISSUE TITLE
Parcel 2: Unexpected token: punc (.)

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#4458]
# 🐛 bug report

Build error when using targets in a monorepo, *same config as https://github.com/parcel-bundler/parcel/issues/4392*

```
🚨 Build failed.
@parcel/optimizer-terser: Unexpected token: punc (.)
SyntaxError: Unexpected token: punc (.)
    at ee (/home/banou/dev/test/node_modules/terser/dist/bundle.min.js:1:19391)
    at c (/home/banou/dev/test/node_modules/terser/dist/bundle.min.js:1:27867)
    at l (/home/banou/dev/test/node_modules/terser/dist/bundle.min.js:1:27958)
    at f (/home/banou/dev/test/node_modules/terser/dist/bundle.min.js:1:28011)
    at G (/home/banou/dev/test/node_modules/terser/dist/bundle.min.js:1:41825)
    at De (/home/banou/dev/test/node_modules/terser/dist/bundle.min.js:1:48112)
    at /home/banou/dev/test/node_modules/terser/dist/bundle.min.js:1:48992
    at ye (/home/banou/dev/test/node_modules/terser/dist/bundle.min.js:1:49007)
    at ze (/home/banou/dev/test/node_modules/terser/dist/bundle.min.js:1:50261)
    at qe (/home/banou/dev/test/node_modules/terser/dist/bundle.min.js:1:50493)
error Command failed with exit code 1.
```

I managed to workaround the bug by removing the `engines` property in the target

```diff
  "targets": {
-    "appModern": {
-      "engines": {
-        "browsers": [
-          "last 1 chrome version"
-        ]
-      }
-    },
+    "appModern": {},
  },
```

Using `^2.0.0-nightly.180`.

**Comment by mischnic** [comment]
I guess this is because terser doesn't support optional chaining
```
echo " export function f(){return x?.y; }" | terser -mc --module
Parse error at 0:1,30
 export function f(){return x?.y; }
                              ^
ERROR: Unexpected token: punc (.)
```
We should definitely add a codeframe to that error.

For the cause itself:
- would you understand that terser doesn't support that syntax and that you need to change your babelrc/browserslist?
- or should we add a hint like "Terser might not support this syntax yes"

**Comment by Banou26** [comment]
I mean, my `.babelrc` does contains `@babel/plugin-proposal-optional-chaining`, shouldn't it be okay ?

**Comment by mischnic** [comment]
Yes, but if removing `targets.appModern.engines` changes the behaviour of babel, then your `.babelrc` isn't actually being used.

**Comment by mischnic** [comment]
This is what the codeframe would look like without using source maps (this is potentially more correct since the unsupported syntax could have been inserted by a build step)

![Bildschirmfoto 2020-04-10 um 12 05 09](https://user-images.githubusercontent.com/4586894/78983700-f9e82080-7b24-11ea-906e-6c1245b286fd.png)

On the other hand, it's a lot prettier displaying the source in this case:

![Bildschirmfoto 2020-04-10 um 12 15 19](https://user-images.githubusercontent.com/4586894/78983701-fa80b700-7b24-11ea-9631-2924bda7ead3.png)

**Comment by Banou26** [comment]
Why not both ? :)
Just kidding.

Maybe have the source display as normal log level, and the final result when using the verbose log level ?

**Comment by mischnic** [comment]
Great idea.

![Bildschirmfoto 2020-04-10 um 12 38 57](https://user-images.githubusercontent.com/4586894/78985119-42550d80-7b28-11ea-9658-22a7f4446dde.png)
(I'm not entirely happy with the formatting of these diagnostics but we have bigger priorities right now.)

Will open a PR once https://github.com/parcel-bundler/source-map/issues/15 is resolved.

**Comment by lukejagodzinski** [comment]
I've just encountered this problem. I'm targeting newest Chrome browser which already has optional chaining. It's no longer proposal. Shouldn't this be just ignored?

**Comment by danieltroger** [comment]
Hello, I don't understand why I can't use `?.` in my code? It works in the browser but I'm getting this error. I'm trying to get parcel to not transpile anything as I want to test the performance impact of transpiling code vs not transpiling code.

**Comment by danieltroger** [comment]
Hello, I found an issue where the terser guys said that they introduced support in a newer version. Parcel uses some version 3.something of terser, which is ancient. Updating terser with `npm install --save terser@5.5.1` did fix the problem for me, but parcel no longer builds without --no-source-maps, it says this instead:

```
[redacted]/node_modules/terser/dist/bundle.min.js:26320
        options.format.source_map.destroy();
                                  ^

TypeError: options.format.source_map.destroy is not a function
    at minify ([redacted]/node_modules/terser/dist/bundle.min.js:26320:35)
    at module.exports ([redacted]/node_modules/parcel/src/transforms/terser.js:46:16)
    at async JSAsset.transform ([redacted]/node_modules/parcel/src/assets/JSAsset.js:137:7)
    at async JSAsset.process ([redacted]/node_modules/parcel/src/Asset.js:216:7)
    at async Pipeline.processAsset ([redacted]/node_modules/parcel/src/Pipeline.js:46:7)
    at async Pipeline.process ([redacted]/node_modules/parcel/src/Pipeline.js:24:23)
    at async Object.run ([redacted]/node_modules/parcel/src/worker.js:15:12)
    at async Bundler.loadAsset ([redacted]/node_modules/parcel/src/Bundler.js:577:19)
    at async Bundler.processAsset ([redacted]/node_modules/parcel/src/Bundler.js:557:5)
    at async PromiseQueue._runJob ([redacted]/node_modules/parcel/src/utils/PromiseQueue.js:48:7)
```

**Comment by abarisain** [comment]
The last terser version that works with parcel is 5.3.2. Fortunately, it supports optional chaining.

5.3.3 changes how the source maps work, and it breaks when used by parcel for some reason. I can't find a workaround for parcel1

**Comment by danieltroger** [comment]
@abarisain I can recommend parcel 2, the scope hoisting is amazing

**Comment by alexburner** [comment]
@danieltroger how did you get `npm install --save terser@5.5.1` to work? I had to use [`npm-force-resolutions`](https://github.com/rogeriochaves/npm-force-resolutions) to successfully overwrite Parcel's 3.17.0 terser version.

**Comment by danieltroger** [comment]
@alexburner I don't remember, I probably edited package.json.

But parcel is basically abandoned. Updating to parcel v2 changed my life. You should update too and it might change yours. Just run `npm install --save parcel@nightly` or change the parcel version in your package.json to `nightly`. You will need to do some reconfiguration but things like multiple targets and scope hoisting will definitely be worth it!

**Comment by ghost** [comment]
I'm still seeing this 

```
$ yarn parcel
yarn run v1.22.17
$ parcel build
🚨 Build failed.

@parcel/optimizer-terser: Unexpected token: punc (?.)

  /Users/ysz/oasis/code/oasis-wallet-web/src/app/components/DateFormatter/index.tsx:19:10
    18 |   second: 'numeric',
  > 19 |   timeZone: process?.env?.NODE_ENV === 'test' ? 'UTC' : undefined,
  >    |          ^ Unexpected token: punc (?.)
    20 | })
    21 | 

  💡 It's likely that Terser doesn't support this syntax yet.

```

I have 

```
$ yarn list --pattern terser
yarn list v1.22.17
├─ @parcel/optimizer-terser@2.3.2
└─ terser@5.12.0
✨  Done in 0.29s.
```
