### ISSUE TITLE
Babel Transformer tries to load @babel/core relative to runtime

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#4729]
# 🐛 bug report

The babel transformer tries to require @babel/core from node_modules/@parcel/runtime-browser-hmr/lib  (“the users babel-core”), but there is no babel-core here. Then Yarn 2 throws

Note: this only fails in workspaces

A regression caused by https://github.com/parcel-bundler/parcel/pull/4526

## 😯 Current Behavior

```
Error: Cannot find module '@babel/core' from '.../berry-repro/.yarn/cache/@parcel-runtime-browser-hmr-npm-2.0.0-nightly.290-56e0fefb14-3.zip/node_modules/@parcel/runtime-browser-hmr/lib'
    at .../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:115:35
    at processDirs (.../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:268:39)
    at loadNodeModules (.../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:293:9)
    at init (.../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:104:16)
    at .../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:90:18
    at maybeRealpath (.../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:41:9)
    at resolve (.../berry-repro/.yarn/cache/resolve-patch-c66c1ab009-3.zip/node_modules/resolve/lib/async.js:84:5)
    at .../berry-repro/.yarn/unplugged/@parcel-utils-npm-2.0.0-nightly.290-51f06aaf7f/node_modules/@parcel/utils/lib/promisify.js:6:13
    at new Promise (<anonymous>)
    at .../berry-repro/.yarn/unplugged/@parcel-utils-npm-2.0.0-nightly.290-51f06aaf7f/node_modules/@parcel/utils/lib/promisify.js:5:12
```

Or
`console: (node:75178) [MODULE_NOT_FOUND] Error: @parcel/runtime-browser-hmr tried to access @babel/core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
`

## 💁 Possible Solution

- Do we need another flag for the babel transformer to know if it should use the bundled babel/core?
- The alternative would be requiring all runtimes to have babel/core installed

## 💻 Code Sample

```sh
yarn set version berry
echo '{"name": "test2", "workspaces": ["parcel"],"private": true}' > package.json
mkdir parcel
cd parcel
yarn init
yarn add -D parcel@nightly
touch index.js
yarn parcel index.js --no-autoinstall
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2
| Yarn | 2

**Comment by gamb** [comment]
This appears to be fixed on parcel@nightly for me…

**Comment by gamb** [comment]
Ah, correction. Worked around with these flags: `yarn run parcel serve --no-hmr --no-source-maps --no-cache --no-autoinstall index.html`

**Comment by jarandmi** [comment]
This happens for me as well, also when i do `parcel build index.html`. Then i get the same error as @mischnic. 
So it's not because of HRM. I tried `parcel build index.html --no-hmr` as well. Then i get `Error: Failed to install @babel/core.`

**Comment by mischnic** [comment]
One solution might be to use `bundledBabelCore` here instead and not call require if `config.searchPath.includes("node_modules")`
https://github.com/parcel-bundler/parcel/blob/a5e234877e42ce98eb2bd38665edf6937af5733a/packages/transformers/babel/src/config.js#L46-L50

**Comment by reinux** [comment]
I'm having this problem as well, both with beta as well as nightly.

`--no-hmr` doesn't do it for me either.

**Comment by LukeTOBrien** [comment]
Hi, I am getting this error too.  
When I add `--no-autoinstall` then Parcel is looking for the package in random folder locations, for eg.  
`Error: Cannot find module '@babel/core' from 'C:\App\UI\Packages\browserinterop\1.1.1\staticwebassets'`

I have `npm install`ed the module `@babel/core` but the no avail.

`browserinterop` happens to be a script I am importing but Parcel shouldn't look for the module there:  
`import "../../UI/Packages/browserinterop/1.1.1/staticwebassets/scripts.js";`

*FYI*  
I am bundeling the static assets for a Blazor project and the browserinterop [is this package](https://www.nuget.org/packages/BrowserInterop/)

**Comment by LukeTOBrien** [comment]
Hello,

I have created a small [repository](https://github.com/LukeTOBrien/parcel2-import-outside) for my issue:  
When I import a file that is in a directory structure outside of my `package.json` the build fails - But Parcel shouldn't be looking there.

```
× Build failed.
Error: Cannot find module '@babel/core' from 'C:parcel2-import-outsideAnotherProject'
```

**Comment by theseyi** [comment]
Is there a temporary workaround that supports HMR for this issue ? Just started evaluating Parcel 2 vs Rollup in a new repo with TypeScript and Yarn Workspaces. Ran into this issue with `parcel serve src/index.html`. However, running `yarn run parcel serve src/index.html --no-hmr` returns a successful outcome.

**Comment by devongovett** [comment]
Should be fixed by #5769 since we no longer resolve `@babel/core` relative to the file being transformed.

**Comment by mijamo** [comment]
This is still an issue for me both on the beta.2 and nightly

**Comment by Fleker** [comment]
Had this issue on beta.2, but not on `2.0.0-rc.0`.
