### PR TITLE
Set TypeScript option esModuleInterop to true by default

### LINKED ISSUE #418: 🐛 Upgrading from 1.2.0 to 1.3.0 breaks moment.js
I'm using typescript and when i upgrade parcel from 1.2.0 to 1.3.1 _(I've tried with 1.3.0 as well)_ the `moment.js` library starts complaining about `moment` not being a function.

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
// package.json
{
  "scripts": {
    "start": "parcel index.html --out-dir temp/"
  },
  "dependencies": {
    "moment": "^2.20.1",
    "parcel-bundler": "1.3.0",
    "typescript": "^2.6.2"
  }
}
```

```html
<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
    <script src="./app.ts"></script>
</body>
</html>
```

```ts
//app.ts
import * as moment from 'moment';

console.log( moment() );
```

_No tsconfig.json_

### 🤔 Expected Behavior

I would expect a `moment` object to be printed to the console.

### 😯 Current Behavior

With parcel `v1.2.0` the `moment` object is printed just fine. But with parcel `v1.3.0` or `v1.3.1` it throws a TypeError. 
```
b6623a1acd83678d58392c21229a4b42.js:6473 Uncaught TypeError: moment is not a function
    at Object.require.2.moment (b6623a1acd83678d58392c21229a4b42.js:6473)
    at newRequire (b6623a1acd83678d58392c21229a4b42.js:41)
    at require.4 (b6623a1acd83678d58392c21229a4b42.js:66)
    at b6623a1acd83678d58392c21229a4b42.js:71
```

### 🔦 Context

Gist of all files used to recreate bug: https://gist.github.com/Olian04/ce4e23c11a17d60c9a39247a879e54c7

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.2.0 & 1.3.0 & 1.3.1
| Node             | 9.3.0
| npm/Yarn         | 5.5.1 / 1.3.2 _(I've tried with both)_
| Operating System | Ubuntu 17.04

### PR DESCRIPTION
**Pull request by fathyb**
This will make TypeScript behave more like the Babel CommonJS plugin. See [TypeScript 2.7 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html) for more info. It'll be ignored if Typescript < 2.7 is used. Users can still opt-out by setting it to false in their `tsconfig.json`.

Fixes #418 and is a better alternative to #530 for TypeScript users.

Please note that it may break existing code bases. From the release note :
> Note: The new behavior is added under a flag to avoid unwarranted breaks to existing code bases. We highly recommend applying it both to new and existing projects. For existing projects, namespace imports (import * as express from "express"; express();) will need to be converted to default imports (import express from "express"; express();).

### CODE REVIEW

**Comment by fathyb** [comment]
@DeMoorJasper any thoughts on also setting `importHelpers` to `true` by default?

**Comment by DeMoorJasper** [comment]
@fathyb won't babel catch most of the exotic syntaxes?
Not sure as i've never used importHelpers, but i guess it should be fine as is
