### ISSUE TITLE
Scheme-relative URLs throw with "Cannot find module"

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#4015]
# 🐛 bug report

When using a scheme relative url in an html document, parcel throws with the following error:

```
🚨  @parcel/resolver-default: Cannot find module '<import>' from '<dirname>'
```

EDIT: This is also the case for CSS and JS assets.

Example
```html
<!DOCTYPE html>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Josefin+Sans:300,600|Raleway:400,500" rel="stylesheet" media="all">
```

## 🤔 Expected Behavior

Should not try to resolve import. I would basically expect the same behavior when used with a protocol like `http:` or `https:`.

## 😯 Current Behavior

It throws.

## 💁 Possible Solution

As it throws in the resolver, maybe it sees this URL as an absolute URL and therefore tries to resolve it: https://github.com/parcel-bundler/parcel/blob/291f3e6815a1a857a6165fafb1691ceeb878b8f6/packages/resolvers/default/src/DefaultResolver.js#L186

This looks like a regression in the latest v2 branch. I first experienced this bug on the 16.11.2019 in a failing pipeline. The pipeline was still working on the 13.11.2019. (The pipeline is always using the latest v2 branch).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2 (https://github.com/parcel-bundler/parcel/commit/9d9c0c695e3c52d64782a49ffae4a2f2c675384b)
| Node             | v12.8.1
| npm         | v6.13.0
| Operating System | Windows (WSL 1 / Ubuntu)

**Comment by DeMoorJasper** [comment]
Potential duplicate of #4005 but this bug report is more descriptive so gonna keep this one open and maybe close the other one.

**Comment by mischnic** [comment]
If this still happens in the CSS `@import()` as well (and maybe even in JS `import x from "//unpkg.com/...`), it should be fixed in the resolver.

Otherwise, we could exclude URLs here instead: https://github.com/parcel-bundler/parcel/blob/291f3e6815a1a857a6165fafb1691ceeb878b8f6/packages/transformers/html/src/dependencies.js#L138-L155

**Comment by garthenweb** [comment]
@mischnic Good hint. I checked that and it is also throwing for JS and CSS assets. I updated the title to make this clearer.
