### ISSUE TITLE
Upgrade to 1.12.4 breaks production due to wrongly reused asset hashes

### ISSUE THREAD

**Issue by neelance** [parcel-bundler/parcel#3896]
# 🐛 bug report

After upgrading from Parcel 1.12.3 to 1.12.4 our application crashed in production with `Cannot find module` errors.

## 🎛 Configuration (.babelrc, package.json, cli command)

No .babelrc.

## 🤔 Expected Behavior

A minor upgrade of parcel-bundler should not break production.

## 😯 Current Behavior

After upgrading from Parcel 1.12.3 to 1.12.4 our application crashed in production with `Cannot find module` errors.

It turned out that the new version generated different bundle contents, but sometimes used the same hash in the asset filename. Since we are using static hosting with infinite caching, this meant that some changed files did not get to production, since the caching assumes that a file with the same hash in the filename also has the same content. Now loading some files built with 1.12.3 and some files with 1.12.4 caused a conflict at runtime, causing the `Cannot find module` error.

The concrete difference between the old and new files is that some of the internal bundle IDs changed, e.g. `lI+P` became `lIP9`.

## 💁 Possible Solution

Either keep the old internal IDs or ensure that the hash in the filename changes.
